export const ERROR="ERROR";

        /* AUTH TYPES */
export const LOGIN="LOGIN";
export const REGISTER="REGISTER";
export const LOGOUT="LOGOUT";
        /* ROOM TYPES */
export const GET_ROOMS="GET_ROOMS";
export const DELETE_ROOM="DELETE_ROOM";
export const UPDATE_ROOM="UPDATE_ROOM";
export const CREATE_ROOM="CREATE_ROOM";
export const GET_ROOM="GET_ROOM";
export const GET_ONE_ROOM="GET_ONE_ROOM";

        /* ROOM TYPES */
export const GET_EMPLOYEES="GET_EMPLOYEES";
export const DELETE_EMPLOYEE="DELETE_EMPLOYEE";
export const UPDATE_EMPLOYEE="UPDATE_EMPLOYEE";
export const CREATE_EMPLOYEE="CREATE_EMPLOYEE";
export const GET_EMPLOYEE="GET_EMPLOYEE";
export const GET_ONE_EMPLOYEE="GET_ONE_EMPLOYEE";

        /* CUSTOMER TYPES */
export const GET_CUSTOMERS="GET_CUSTOMERS";
export const DELETE_CUSTOMER="DELETE_CUSTOMER";
export const UPDATE_CUSTOMER="UPDATE_CUSTOMER";
export const CREATE_CUSTOMER="CREATE_CUSTOMER";
export const GET_CUSTOMER="GET_CUSTOMER";
export const GET_ONE_CUSTOMER="GET_ONE_CUSTOMER";
export const GET_ONE_CUSTOMER_WITH_EXTRAS="GET_ONE_CUSTOMER_WITH_EXTRAS";
export const GET_ONE_CUSTOMER_WITH_MEALS="GET_ONE_CUSTOMER_WITH_MEALS";
export const GET_ONE_CUSTOMER_WITH_SERVICES="GET_ONE_CUSTOMER_WITH_SERVICES";
export const ADD_EXTRA_TO_CUSTOMER="ADD_EXTRA_TO_CUSTOMER";
export const ADD_MEAL_TO_CUSTOMER="ADD_MEAL_TO_CUSTOMER";
export const ADD_SERVICE_TO_CUSTOMER="ADD_SERVICE_TO_CUSTOMER";
export const DELETE_EXTRA_FROM_CUSTOMER="DELETE_EXTRA_FROM_CUSTOMER";
export const DELETE_MEAL_FROM_CUSTOMER="DELETE_MEAL_FROM_CUSTOMER";
export const DELETE_SERVICE_FROM_CUSTOMER="DELETE_SERVICE_FROM_CUSTOMER";

        /* SERVICE TYPES */
export const GET_SERVICES="GET_SERVICES";
export const DELETE_SERVICE="DELETE_SERVICE";
export const UPDATE_SERVICE="UPDATE_SERVICE";
export const CREATE_SERVICE="CREATE_SERVICE";
export const GET_SERVICE="GET_SERVICE";
export const GET_ONE_SERVICE="GET_ONE_SERVICE";

         /* MEAL TYPES */
export const GET_MEALS="GET_MEALS";
export const DELETE_MEAL="DELETE_MEAL";
export const UPDATE_MEAL="UPDATE_MEAL";
export const CREATE_MEAL="CREATE_MEAL";
export const GET_MEAL="GET_MEAL";
export const GET_ONE_MEAL="GET_ONE_MEAL";

         /* EXTRA TYPES */
export const GET_EXTRAS="GET_EXTRAS";
export const DELETE_EXTRA="DELETE_EXTRA";
export const UPDATE_EXTRA="UPDATE_EXTRA";
export const CREATE_EXTRA="CREATE_EXTRA";
export const GET_EXTRA="GET_EXTRA";
export const GET_ONE_EXTRA="GET_ONE_EXTRA";

         /* BILLS TYPES */
export const GET_BILLS="GET_BILLS";
export const DELETE_BILL="DELETE_BILL";
export const UPDATE_BILL="UPDATE_BILL";
export const CREATE_BILL="CREATE_BILL";
export const GET_BILL="GET_BILL";
export const GET_ONE_BILL="GET_ONE_BILL";