export const ERROR="ERROR";

        /* AUTH TYPES */
export const LOGIN="LOGIN";
export const REGISTER="REGISTER";
export const LOGOUT="LOGOUT";
        /* ROOM TYPES */
export const GET_ROOMS="GET_ROOMS";
export const DELETE_ROOM="DELETE_ROOM";
export const UPDATE_ROOM="UPDATE_ROOM";
export const CREATE_ROOM="CREATE_ROOM";
export const GET_ROOM="GET_ROOM";
export const GET_ONE_ROOM="GET_ONE_ROOM";

        /* ROOM TYPES */
export const GET_EMPLOYEES="GET_EMPLOYEE";
export const DELETE_EMPLOYEE="DELETE_EMPLOYEE";
export const UPDATE_EMPLOYEE="UPDATE_EMPLOYEE";
export const CREATE_EMPLOYEE="CREATE_EMPLOYEE";
export const GET_EMPLOYEE="GET_EMPLOYEE";
export const GET_ONE_EMPLOYEE="GET_ONE_EMPLOYEE";

        /* CUSTOMER TYPES */
export const GET_CUSTOMERS="GET_CUSTOMER";
export const DELETE_CUSTOMER="DELETE_CUSTOMER";
export const UPDATE_CUSTOMER="UPDATE_CUSTOMER";
export const CREATE_CUSTOMER="CREATE_CUSTOMER";
export const GET_CUSTOMER="GET_CUSTOMER";
export const GET_ONE_CUSTOMER="GET_ONE_CUSTOMER";